workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

stages:
  - test

test-job:
  stage: test
  image: golang:latest
  script:
    - chmod +x ./init-repo.sh
    - ./init-repo.sh
    - ./local-test-script.sh
